local packager = require("packager")
-- Install breadcrumbs
packager.install_package("dropbar", "Bekaboo/dropbar.nvim")
-- Load breadcrumbs
local dropbar = packager.try_require("dropbar")
if dropbar then
  dropbar.setup({
    icons = vim.g.nerd_font and {} or {
      kinds = {
        symbols = {
          Array = "(arr)",
          BlockMappingPair = "(blkmappair)",
          Boolean = "(bool)",
          BreakStatement = "(brk)",
          Call = "(call)",
          CaseStatement = "(case)",
          Class = "(cls)",
          Constant = "(const)",
          Constructor = "(constr)",
          ContinueStatment = "(cont)",
          Copilot = "(copilot)",
          Declaration = "(decl)",
          Delete = "(del)",
          DoStatement = "(do)",
          Element = "(elem)",
          Enum = "(enum)",
          EnumMember = "(emumMem)",
          Event = "(evt)",
          Field = "(fld)",
          File = "(f)",
          Folder = "(d)",
          ForStatement = "(for)",
          Function = "(fn)",
          GotoStatement = "(goto)",
          Identifier = "(ident)",
          IfStatement = "(if)",
          Interface = "(intf)",
          Keyword = "(kwd)",
          List = "(list)",
          Log = "(log)",
          Lsp = "(lsp)",
          Macro = "(mac)",
          MarkdownH1 = "(h1)",
          MarkdownH2 = "(h2)",
          MarkdownH3 = "(h3)",
          MarkdownH4 = "(h4)",
          MarkdownH5 = "(h5)",
          MarkdownH6 = "(h6)",
          Method = "(mth)",
          Module = "(mod)",
          Namespace = "(ns)",
          Null = "(nul)",
          Number = "(num)",
          Object = "(obj)",
          Operator = "(oper)",
          Package = "(pkg)",
          Pair = "(pair)",
          Property = "(prop)",
          Reference = "(ref)",
          Regex = "(regex)",
          Repeat = "(rep)",
          Return = "(ret)",
          Rule = "(rule)",
          RuleSet = "(ruleset)",
          Scope = "(scope)",
          Section = "(sec)",
          Snippet = "(snip)",
          Specifier = "(spec)",
          Statement = "(stmt)",
          String = "(str)",
          Struct = "(struct)",
          SwitchStatement = "(swit)",
          Table = "(tbl)",
          Terminal = "(term)",
          Text = "(txt)",
          Type = "(type)",
          TypeParameter = "(typepar)",
          Unit = "(unit)",
          Value = "(val)",
          Variable = "(var)",
          WhileStatement = "(whl)",
        },
      },
      ui = {
        bar = {
          separator = "> ",
          extends = "...",
        },
        menu = {
          separator = " ",
          indicator = "> ",
        },
      },
    },
  })
end
